name: openai whisper
on:
  push:
    branches:
      - main
jobs:
  build_with_signing:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install openai whisper
        run: pip install -U openai-whisper

      - name: install ffmpeg
        run: sudo apt install ffmpeg

      - name: run model
        run: |
          whisper sample1.mp3 --model small

      - name: Upload Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: sample1.txt
